public with sharing class ClaseNivelDeRiesgo {
    public Decimal CodRiesgo {get;set;} 
    public string NivelRiesgo {get;set;}   
    public Decimal Porcentaje_Inicial {get;set;}  
    public Decimal Porcentaje_Final {get;set;} 
    public Decimal RiesgoPonderacion {get;set;} 
    
    
    /* public ClaseNivelDeRiesgo(string NivelRiesgo,Decimal CodRiesgo, Decimal Porcentaje_Inicial,Decimal Porcentaje_Final, Decimal RiesgoPonderacion)
        
    {
        this.NivelRiesgo=NivelRiesgo;
        this.CodRiesgo = CodRiesgo;
        this.Porcentaje_Inicial = Porcentaje_Inicial;
        this.Porcentaje_Final = Porcentaje_Final;
        this.RiesgoPonderacion = RiesgoPonderacion; 
    }    
*/
}