public with sharing class classPersonas {
	 public String tipoIdentificacion { get; set; }
    public String identidad { get; set; }
    public String primerNombre { get; set; }
    public String segundoNombre { get; set; }
    public String primerApellido { get; set; }
    public String segundoApellido { get; set; }
    public DateTime fechaNacimiento { get; set; }
    public String sexo { get; set; }
    public String estadoCivil { get; set; }

}