public class classGestionesBac {
	public String tipoGestion { get; set; }  //variable nueva 
    public String identificacion { get; set; }
    public String nombreCliente { get; set; }
    public String email { get; set; }
    public String celular { get; set; }
    public String sexo { get; set; }
    public String servicio { get; set; }
    public String cuentaPensiones { get; set; }
    public String tipoTarjeta { get; set; }
    public String nombreTarjetaHabiente { get; set; }
    public String numeroTarjeta { get; set; }
    public String fechaExpiracion { get; set; }
    public String bancoTarjeta { get; set; }
    public String diaCobro { get; set; }
    public String montoDebito { get; set; }
    public String estadoDebito { get; set; } //variable nueva
}