public class claseFactoresDeRiesgo {
    //VARIABLES PARA EL PORCENTAJE DE RIESGO
    public string  TipoCliente {get;set;}
    public String RiesgoTipoCliente {get;set;}
    public String RiesgoTipoPersona {get;set;}
    public String RiesgoTipoDocumento {get;set;}
    public String RiesgoFechaAfiliacion {get;set;}
    public String RiesgoFechaNacimiento {get;set;}
    public String RiesgoTrabaja {get;set;}
    public String RiesgoOcupacion {get;set;}
    public String RiesgoListaExcepciones {get;set;}
    public String RiesgoListaPep {get;set;}
    public String Riesgoproducto {get;set;}
    public String Riesgocanal {get;set;}
    public String RiesgoMunicipalidad {get;set;}
    public String RiesgoNacionalidad {get;set;}
    //JR
    public String RiesgoFechaConstitucion {get;set;}
    public String RiesgoGiroEmpresa {get;set;}
    public String RiesgoUbicacionEmpresa {get;set;}
    
    //VARIABLES PARA EL PORCENTAJE DE RIESGO
    public String ValorRiesgoTipoCliente {get;set;}
    public String ValorRiesgoTipoPersona {get;set;}
    public String ValorRiesgoTipoDocumento {get;set;}
    public String ValorRiesgoFechaAfiliacion {get;set;}
    public String ValorRiesgoFechaNacimiento {get;set;}
    public String ValorRiesgoTrabaja {get;set;}
    public String ValorRiesgoOcupacion {get;set;}
    public String ValorRiesgoListaExcepciones {get;set;}
    public String ValorRiesgoListaPep {get;set;}  
    public String ValorRiesgoproducto {get;set;}
    public String ValorRiesgocanal {get;set;}
    public String ValorRiesgoMunicipalidad {get;set;}
    public String ValorRiesgoNacionalidad {get;set;}
    //JR
    public String ValorRiesgoFechaConstitucion {get;set;}
    public String ValorRiesgoGiroEmpresa {get;set;}
    public String ValorRiesgoUbicacionEmpresa {get;set;}
    

}