public class classcambiopignorados {
    public List<classcambiopignorados> ListPignorados { get; set; }
public decimal m_pignorado { get; set; }
        public DateTime fpignoracion { get; set; }
        public DateTime fliberacion { get; set; }
    	public string num_prest { get; set; }
        public string num_prest1 { get; set; }
        public string est_pig { get; set; }
        public decimal sec_pig { get; set; }
        public decimal tot_fondos_pig { get; set; }
        public decimal m_prestamo { get; set; }
    public string nombrepig { get; set; }
	public string codcuenta { get; set; }
    public string id_pign { get; set; }
    public Transient Blob referenciaImg {get;set;}
    
}