public with sharing class ClassReferenciaxClienteT24 {

   	public string primerNomRef {get;set;}                
    public string segundoNomRef {get;set;}
    public string primerApeRef {get;set;}
    public string segundoApeRef {get;set;}                
    public string telefonoRef {get;set;}
    
    public ClassReferenciaxClienteT24 (String primerNomRef, String segundoNomRef, String primerApeRef, 
                                  String segundoApeRef, String telefonoRef){
        		this.primerNomRef = primerNomRef;                
                this.segundoNomRef = segundoNomRef;
                this.primerApeRef = primerApeRef;
                this.segundoApeRef = segundoApeRef;                
                this.telefonoRef = telefonoRef;
    }
}