public class classBeneficiarioT24 {

//****************************Informacion de beneficiario**************************************************************************
                public string primerNomBenf {get;set;}
                public string segundoNomBenf {get;set;}
                public string primerApeBenf {get;set;}
                public string segundoApeBenf {get;set;}
                public string parentescoBenf {get;set;}
                public string porcentajeBenf {get;set;}
    			public string Grado {get;set;}
    			
 
    public classBeneficiarioT24 (String primerNomBenf, String segundoNomBenf, String primerApeBenf, String segundoApeBenf, 
                              String parentescoBenf, String porcentajeBenf, string Grado){
                
                this.primerNomBenf = primerNomBenf;
                this.segundoNomBenf = segundoNomBenf;
                this.primerApeBenf = primerApeBenf;
                this.segundoApeBenf = segundoApeBenf;
                this.parentescoBenf = parentescoBenf;
                this.porcentajeBenf = porcentajeBenf;
               this.Grado 			= Grado;
                                 
  
                                  }
}