public with sharing class classECPortada {
	public String nombreCliente { get; set; }
	public string identidad { get; set; }
    public String emailCliente { get; set; }
	public Boolean fondosObligatorios { get; set; }
    public String totalPension { get; set; }
    public String coberturaLaboral { get; set; }
    public String fondosLempiras { get; set; }
    public String fondosDolares { get; set; }  
    public String fechaCierre { get; set; }  
}