public with sharing class classBitacora {
	
	public String numeroCaso { get; set; }
    public String nombreCaso { get; set; }
    public DateTime fechaCaso { get; set; }
    public String valorAnterior { get; set; }
    public String valorNuevo { get; set; }
    public String usuarioCaso { get; set; }
    public String usuarioAprueba { get; set; }
    public DateTime fechaAprueba { get; set; }
    public DateTime fechaModificacion { get; set; }    
}