public with sharing class classECMensual {
	public String nombreCliente { get; set; }
    public String emailCliente { get; set; }
    public String sexo {get;set;}
    public String fpcTrabajo { get; set; }
    public String misAportes { get; set; }
    public String miEmpleador { get; set; }
    public String fechaAcumulado { get; set; }
    public String saldoAcumulado { get; set; }
    public String grafico { get; set; }
    public string urlPichingo{get;set;}
}