public with sharing class classUsuarioJuridico {
    public string CuentaMostrar {get;set;}
    public string pc_codCuenta {get;set;}
    public string tipoUsuarioJuridico { get; set; }
    public string PEP { get; set; }
    //public string AML  { get; set;}
    public string FATCA { get; set; }
    public string activo { get; set; }
    public string causa { get; set; }
    public string tipoId { get; set; }
    public string numeroId { get; set; }
    public string nombreRazon { get; set; }
    public string telefono { get; set; }
    public string pConstitucion { get; set; }
    public string procedenciaFondo { get; set; }
    public string calificacionRiesgo { get; set; }
    public string diligenciaAplicada { get; set; }
    public string pais { get; set; }
    public string departamento { get; set; }
    public string municipio { get; set; }
    public string colonia { get; set; }
    public string calle { get; set; }
    public string idFormulario { get; set; }
    public string codPromotor { get; set; }
    public string codProducto { get; set; }
    public string codSubproducto { get; set; }
    public string estatal { get; set; }
    public string sector { get; set; }
    public string claseSociedad { get; set; }
    public string lucrativa { get; set; }
    public string formaPago { get; set; }
    public string periodicidad { get; set; }
    public string IdRepresentanteLegal { get; set; }
    public string primerNombreR { get; set; }
    public string segundoNombreR { get; set; }
    public string primerApellidoR { get; set; }
    public string segundoApellidoR { get; set; }   
}