@isTest
private class ConvertirNumerosTest {

    static testMethod void ConvertirNumeros() {
        
          
            String x = ConvertirNumeros.convertirLetras(1000000000);
            x = ConvertirNumeros.convertirLetras(987654321);
            x = ConvertirNumeros.convertirLetras(876543210);
            x = ConvertirNumeros.convertirLetras(76543210);
            x = ConvertirNumeros.convertirLetras(6543210);
            x = ConvertirNumeros.convertirLetras(543210);
            x = ConvertirNumeros.convertirLetras(43210);
            x = ConvertirNumeros.convertirLetras(3210);
            x = ConvertirNumeros.convertirLetras(210);
            x = ConvertirNumeros.convertirLetras(10);
            x = ConvertirNumeros.convertirLetras(11);
            x = ConvertirNumeros.convertirLetras(21);
            x = ConvertirNumeros.convertirLetras(31);
            x = ConvertirNumeros.convertirLetras(41);
            x = ConvertirNumeros.convertirLetras(51);
            x = ConvertirNumeros.convertirLetras(61);
            x = ConvertirNumeros.convertirLetras(71);
            x = ConvertirNumeros.convertirLetras(81);
            x = ConvertirNumeros.convertirLetras(91);
            x = ConvertirNumeros.convertirLetras(100);
            
            x = ConvertirNumeros.convertirLetras(101);
            x = ConvertirNumeros.convertirLetras(201);
            x = ConvertirNumeros.convertirLetras(301);
            x = ConvertirNumeros.convertirLetras(401);
            x = ConvertirNumeros.convertirLetras(501);
            x = ConvertirNumeros.convertirLetras(601);
            x = ConvertirNumeros.convertirLetras(701);
            x = ConvertirNumeros.convertirLetras(801);
            x = ConvertirNumeros.convertirLetras(901);
            x = ConvertirNumeros.convertirLetras(1000);
        
    }

}