public class FieldsAHManagement {
	public String ACCOUNT_NUMBER;
    public String CUSTOMER_ID;
    public String ACCOUNT_NAME;
    public String CATEGORY;
    public String CURRENCY_VAL;
    public String LIMIT_REF;
    public String RESTRICTIONS;
    public String ALT_ACCOUNT;   
    public String OPENING_DATE;
    public String OPERATION_TYPE;
    public String ACCOUNT_OFFICER;
    public String BRANCH_CODE;
    public String LEGAL_ID;
    public String REQUIRED_SIGNATURES;
    public String SIGNATURE_DESC;
    public String INACTIVE_MARKER;
}