public class FieldsBankManagement {
	public String tipoGestion;
    public String identificacion;
    public String moneda;
    public String fechaInicio;
    public String periodicidad;
    public String cuentaBancaria;
    public String diaCobro;
    public String montoDebito;
    
    public String pctipoid;
    public String pcnroid;
    public String cuenta;
    public String pcprimernombre; 
    public String pcprimerapellido;
    public String pcmail;
    public String pnnrocertificado;
    public String tipoFondo;
    public String frecuencia;
    public String pcformapago;
    public String pccuentapago;
    public String diaPago;
    public String pcMes;
    public String pcAnio;
    public Double pcMonto;
    public String pcPOS;
    public String pcTarjetaHabiente;
    public String pcTipoTarjeta;
    public String pcBanco;
    public Date pcNuevaFecha;
    public String pcpromotor;
    
    public String EntitlementValue;
    
    public List<FieldsBankManagement> fieldsList;
    
    public String CARD_HOLDER_LEGAL_ID;
    public String ACCOUNT_HOLDER_LEGAL_ID;
    public String ACCOUNT_NUMBER;
    public String CARD_STATUS; 
}