public class pagoRetirosC {
	public string referencia { get; set; }
   	public string codCuenta { get; set; }
    public string nombreCliente { get; set; }
    public Decimal numeroCaso { get; set; }
    public Decimal monMovimto { get; set; }
    public Decimal monRetirar { get; set; }
    public DateTime fecMovimto { get; set; }
    public DateTime fecSYSDE { get; set; }
    public Decimal comparacion { get; set; }
    public string fPago { get; set; }
    public Decimal comparaFecha { get; set; }
    public string descripcion { get; set; }
    public string cuentaBancaria { get; set; }
    public string cuentaDestino { get; set; }
    public Decimal monTotal { get; set; }
    public string bancoDestino { get; set; }
    public string tCuenta { get; set; }
    public string moneda { get; set; }
    public Decimal tsp { get; set; }
    public Decimal ach { get; set; }
    public Decimal ck { get; set; }
}