@isTest
public class testClasesNatural {
    static testMethod void classUsuarioNatural(){
    test.startTest();
        classUsuarioNatural natural = new classUsuarioNatural();
        natural.tipoUsuarioNatural = 'N';
        natural.noDomicilio = '';
        natural.PEP = '';
        natural.AML = '';
        natural.FATCA = '';
        natural.tipoId = '1';
        natural.numeroId = '0801-1993-15869';
        natural.primerNombre = 'MARIA';
        natural.segundoNombre = 'JOSEFA';
        natural.primerApellido = 'MARTINEZ';
        natural.segundoApellido = 'MEJIA';
        natural.fechaNacimiento = null;
        natural.nacionalidad = 'HONDUREÑA';
        natural.telefono = '99456986';
        natural.pais = '074';
        natural.colonia = '000';
        natural.departamento = '000';
        natural.municipio = '000';
        natural.calleDetalle = 'PAYAQUI';
        natural.procedenciaFondos = 'null';
        natural.nivelRiesgo = '2';
        natural.debidaDiligencviaAplicada = '1';
        natural.numeroIdentificacion = '0801-1994-11013';
        natural.numeroCuenta = '51600';
        natural.nombreCompleto = 'null';
    test.stopTest();        
    }

}