@isTest
public class testApiRiesgo {
    static testMethod void ControllerApiValidaRiesgo(){ 
        test.startTest();
        controllerApiValidaRiesgo.NivelRiesgo(null);
        controllerApiValidaRiesgo.NivelRiesgoJ(null);
        
        ContenidoValidaNivelJ Validaj = new ContenidoValidaNivelJ('',null,'','','','','','','','');
        ContenidoValidaNivel Valida = new ContenidoValidaNivel('',null,'','','','','','', '','','', '','');
        
        //enviarValidarNivelJ env = new enviarCambioAsesor(validaDatos); 
          //                      
                                    
                       
    }
}