public class test123 {

    public String gf {get;set;}
    
    public test123(){
        gf = '<table style="color: red; position: absolute; top: 150px;left: 230px; font-size: 10px;" > <tr> <td> Hola 1 </td> <td> Hola 2 </td> </tr> <tr> <td> Hola 1 </td> <td> Hola 2 </td> </tr> </table> <img style="height: 500px; width: 300px;" src="https://ficohsafpc--stagefpc--c.visualforce.com/resource/1578345573000/Banner1?">';
    }
}